import { Box, Center, Grid, Group, Stack, Text } from '@mantine/core';
import Head from 'next/head';
import Image from 'next/image';
import { useRouter } from 'next/router';
import { Header } from '~/features/layout/LayoutHeader';
import styles from './index.module.css';

export default function Home() {
	const router = useRouter();

	return (
		<>
			<Head>
				<title>Delivery Tracking System</title>
				<meta name='description' content='Generated by phyo_yarzar' />
			</Head>

			<main className={styles.root}>
				<Header />

				<div className={styles.main}>
					<div className={styles.container}>
						<Grid>
							<Grid.Col span={8}>
								<Stack spacing={40}>
									<Center>
										<h1 className={styles.title}>
											<Box
												mb={4}
												className={styles.pinkSpan}
												component='span'
												display={'block'}
												fz={36}
											>
												Welcome to our
											</Box>
											<span className={styles.pinkSpan}>
												delivery service system
											</span>
										</h1>
									</Center>

									<Text color='gray.6'>
										We take the security of your products seriously. We
										understand that every package entrusted to us represents a
										commitment to deliver not just goods, but also peace of
										mind. We have implemented a comprehensive set of measures to
										safeguard your deliveries at every step of their journey.
									</Text>

									<Group spacing={50} mt={16}>
										<div
											className={styles.card}
											onClick={() => void router.push('/bookings')}
										>
											<h3 className={styles.cardTitle}>Booking →</h3>
											<div className={styles.cardText}>
												Book the parcel to send wherever you want
											</div>
											{/* <div className={styles.cardText}>
								Customers can track the status of their pickups in real-time,
								ensuring a smooth and reliable shipping experience. Say goodbye
								to long lines and travel to drop-off points – Pick-Up Bookings
								brings shipping convenience right to your doorstep.
							</div> */}
										</div>
										<div
											className={styles.card}
											onClick={() => void router.push('/search-products')}
										>
											<h3 className={styles.cardTitle}>Search →</h3>
											<div className={styles.cardText}>
												Search your parcels/products to see where it is
											</div>
											{/* <div className={styles.cardText}>
								Track your routes by ensuring the safe and timely delivery of
								your products to customers. With real-time tracking
								capabilities, the service empowers users to trace the location,
								status, and movement of their goods from production to delivery
							</div> */}
										</div>
									</Group>
								</Stack>
							</Grid.Col>

							<Grid.Col span={4}>
								<Image
									src='/img/delivery-man.svg'
									alt='delivery man'
									width={400}
									height={580}
								/>
							</Grid.Col>
						</Grid>
					</div>
				</div>
			</main>
		</>
	);
}
